# Generated by Django 5.2.12 on 2026-07-17 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('publisher_identity', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.JSONField(default=dict)),
                ('component_schema_version', models.PositiveIntegerField(default=1)),
                ('registration_version', models.PositiveBigIntegerField(default=1)),
                ('registration_hash', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('source_as_of', models.DateTimeField(blank=True, null=True)),
                ('assessment_policy_version', models.CharField(blank=True, default='', max_length=100)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'snapper_current_component',
                'ordering': ['scope', 'name'],
                'indexes': [models.Index(fields=['scope', 'active', 'name'], name='snapper_comp_scope_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'name'), name='snapper_comp_scope_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SystemSnap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=100)),
                ('snap_time', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('snap_schema_version', models.PositiveIntegerField(default=1)),
                ('capture_policy', models.CharField(max_length=100)),
                ('encoding', models.CharField(choices=[('full', 'Full'), ('delta', 'Component delta')], default='full', max_length=16)),
                ('reasons', models.JSONField(default=list)),
                ('changed_components', models.JSONField(default=list)),
                ('component_revisions', models.JSONField(default=dict)),
                ('registration_versions', models.JSONField(default=dict)),
                ('component_hashes', models.JSONField(default=dict)),
                ('state_hash', models.CharField(max_length=64)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'snapper_system_snap',
                'ordering': ['scope', '-snap_time'],
                'indexes': [models.Index(fields=['scope', '-snap_time'], name='snapper_snap_scope_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'snap_time'), name='snapper_snap_scope_time_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CaptureCursor',
            fields=[
                ('scope', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('observed_revisions', models.JSONField(default=dict)),
                ('observed_hashes', models.JSONField(default=dict)),
                ('latest_boundary_at', models.DateTimeField(blank=True, null=True)),
                ('latest_check_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_progress', models.PositiveIntegerField(default=0)),
                ('scheduler_result', models.JSONField(default=dict)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('coverage_gap_started_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('latest_snap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capture_cursors', to='snapper_ai.systemsnap')),
            ],
            options={
                'db_table': 'snapper_capture_cursor',
                'ordering': ['scope'],
            },
        ),
    ]
