# Generated by Django 5.2.12 on 2026-08-02 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapper_ai', '0002_systemsnap_recovery_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=100)),
                ('episode_id', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(blank=True, default='', max_length=100)),
                ('builder_identity', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('episode_schema_version', models.PositiveIntegerField(default=1)),
                ('event_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'snapper_episode',
                'ordering': ['scope', '-started_at'],
                'indexes': [models.Index(fields=['scope', '-started_at'], name='snapper_episode_scope_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'episode_id'), name='snapper_episode_scope_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveBigIntegerField()),
                ('event_time', models.DateTimeField()),
                ('kind', models.CharField(max_length=100)),
                ('participant_id', models.CharField(max_length=255)),
                ('counterpart_id', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='snapper_ai.episode')),
            ],
            options={
                'db_table': 'snapper_episode_event',
                'ordering': ['episode', 'seq'],
                'indexes': [models.Index(fields=['episode', 'event_time'], name='snapper_epi_event_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('episode', 'seq'), name='snapper_epi_event_seq_uniq')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_id', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(blank=True, default='', max_length=100)),
                ('born_at', models.DateTimeField(blank=True, null=True)),
                ('died_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='snapper_ai.episode')),
            ],
            options={
                'db_table': 'snapper_episode_participant',
                'ordering': ['episode', 'born_at'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'participant_id'), name='snapper_epi_part_uniq')],
            },
        ),
    ]
